### ISSUE TITLE
broken for 8?

### ISSUE THREAD

**Issue by gillyspy** [medicomp/eslint-html-parser#8]
``` Oops! Something went wrong! :(

ESLint: 8.9.0

TypeError: Cannot read properties of undefined (reading 'length')
Occurred while linting /Users/gerald.gillespie/Inscio, LLC/snippets/requirejs-config-patterns/com.suitecoders.kp9oeb/src/Objects/basic.html:2
Rule: "strict"
    at getUseStrictDirectives (/Users/gerald.gillespie/Inscio, LLC/snippets/node_modules/eslint/lib/rules/strict.js:27:36)
    at Program (~/snippets/node_modules/eslint/lib/rules/strict.js:238:45)
    at ruleErrorHandler (~snippets/node_modules/eslint/lib/linter/linter.js:1107:28)
    at ~/snippets/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (~/snippets/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (~/snippets/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (~/snippets/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (~/snippets/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (~/snippets/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

basic.html is super basic

**Comment by gillyspy** [comment]
just parsing works: see https://codesandbox.io/s/fancy-snowflake-yu5oh2?file=/src/index.js
so i guess there is a conflict with my top-level settings so setting this worked to not use the top level
`  'root':true `
